"""
Backend models package.
Re-exports legacy (Scenario, CashflowResult, etc.) and canonical lease schema.
"""

from .legacy import (
    OpexMode,
    OneTimeCost,
    TerminationOption,
    RentStep,
    Scenario,
    RenewalInput,
    RelocationInput,
    GenerateScenariosRequest,
    GenerateScenariosResponse,
    ReportBranding,
    ReportScenarioEntry,
    CreateReportRequest,
    CreateReportResponse,
    ExtractionResponse,
    ExtractionSource,
    ExtractedField,
    LeaseExtraction,
    CashflowResult,
    ReportMeta,
    ReportRequest,
)
from .canonical_lease import (
    CanonicalLease,
    RentScheduleStep,
    PhaseInStep,
    FreeRentPeriod,
    RentAbatement,
    RenewalOption,
    OptionRentStructure,
    LeaseType,
    EscalationType,
    ExpenseStructureType,
)
from .canonical_response import (
    CanonicalComputeResponse,
    CanonicalMetrics,
    MonthlyRow,
    AnnualRow,
    NormalizerResponse,
)

__all__ = [
    "OpexMode",
    "OneTimeCost",
    "TerminationOption",
    "RentStep",
    "Scenario",
    "RenewalInput",
    "RelocationInput",
    "GenerateScenariosRequest",
    "GenerateScenariosResponse",
    "ReportBranding",
    "ReportScenarioEntry",
    "CreateReportRequest",
    "CreateReportResponse",
    "ExtractionResponse",
    "ExtractionSource",
    "ExtractedField",
    "LeaseExtraction",
    "CashflowResult",
    "ReportMeta",
    "ReportRequest",
    "CanonicalLease",
    "RentScheduleStep",
    "PhaseInStep",
    "FreeRentPeriod",
    "RentAbatement",
    "RenewalOption",
    "OptionRentStructure",
    "LeaseType",
    "EscalationType",
    "ExpenseStructureType",
    "CanonicalComputeResponse",
    "CanonicalMetrics",
    "MonthlyRow",
    "AnnualRow",
    "NormalizerResponse",
]
